version: "2"
linters:
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
